{% set name = "adaflow" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/modelscope/AdaFlow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 908d3075001ea8fa8390490c54b047a7eb09cb023234af205c963294fcfd194e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - python
    - setuptools
    - cmake
    - make
  host:
    - glib
    - gstreamer 1.22.0
    - gst-plugins-base 1.22.0
    - gst-plugins-good 1.22.0
    - gst-plugins-bad 1.22.0
    - gst-plugins-ugly  1.22.0
    - gst-python 1.22.0
  run:
    - {{ pin_compatible("glib") }}


test:
  commands:
    - test -f $PREFIX/lib/libflowmetadata$SHLIB_EXT
    - test -f $PREFIX/lib/gstreamer-1.0/libflow_gst_plugin$SHLIB_EXT
    - gst-inspect-1.0 flow_gst_plugin

about:
  home: https://github.com/modelscope/AdaFlow
  license: Apache-2.0
  license_file: LICENSE
  summary: 'AdaFlow: Pipeline Frameworks for Deep-Learning Applications'

extra:
  recipe-maintainers:
    - robinqu
