{% set name = "adaflow" %}
{% set version = "v0.0.2" %}
{% set processor = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [not osx]
{% set processor = "cpu" %}  # [osx]

{% set build = build + 100 if processor == "gpu" else build %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/modelscope/AdaFlow/releases/download/{{ version }}/archive_all.tar.gz"
  sha256: 89f2c6acbac180f31662d72997e852c9efb0975dbc5604978cdcd8faa8229ec5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [not osx and cuda_compiler_version != "None"]
    - pkg-config
    - python
    - setuptools
    - cmake
    - make
  host:
    - glib
    - gstreamer 1.22.0
    - gst-plugins-base 1.22.0
    - gst-plugins-good 1.22.0
    - gst-plugins-bad 1.22.0
    - gst-plugins-ugly  1.22.0
    - gst-python 1.22.0
  run:
    - {{ pin_compatible("glib") }}
    - __cuda  # [not osx and cuda_compiler_version != "None"]


test:
  commands:
    - "test -f $PREFIX/lib/gstreamer-1.0/libflow_gst_plugin$SHLIB_EXT"
    - "test -f $PREFIX/lib/libflow_gst_plugin$SHLIB_EXT"
    - "gst-inspect-1.0 flow_gst_plugin"

about:
  home: "https://github.com/modelscope/AdaFlow"
  license: Apache-2.0
  license_file: LICENSE
  summary: "AdaFlow: Pipeline Frameworks for Deep-Learning Applications"

extra:
  recipe-maintainers:
    - robinqu
